# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vector_database.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15vector_database.proto\x12\x0fvector_database\"<\n\x15UploadDocumentRequest\x12\x10\n\x08pdf_data\x18\x01 \x01(\x0c\x12\x11\n\tfile_name\x18\x02 \x01(\t\")\n\x16UploadDocumentResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"6\n\x16SearchDocumentsRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\r\n\x05top_k\x18\x02 \x01(\x05\"I\n\x17SearchDocumentsResponse\x12.\n\x07results\x18\x01 \x03(\x0b\x32\x1d.vector_database.SearchResult\"i\n\x0cSearchResult\x12\x16\n\x0e\x64ocument_index\x18\x01 \x01(\x05\x12\x13\n\x0b\x63hunk_index\x18\x02 \x01(\x05\x12\x12\n\nchunk_text\x18\x03 \x01(\t\x12\x18\n\x10\x64ocument_summary\x18\x04 \x01(\t\"$\n\x14SummarizeTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"(\n\x15SummarizeTextResponse\x12\x0f\n\x07summary\x18\x01 \x01(\t2\xb9\x02\n\x0eVectorDatabase\x12\x61\n\x0eUploadDocument\x12&.vector_database.UploadDocumentRequest\x1a\'.vector_database.UploadDocumentResponse\x12\x64\n\x0fSearchDocuments\x12\'.vector_database.SearchDocumentsRequest\x1a(.vector_database.SearchDocumentsResponse\x12^\n\rSummarizeText\x12%.vector_database.SummarizeTextRequest\x1a&.vector_database.SummarizeTextResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vector_database_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_UPLOADDOCUMENTREQUEST']._serialized_start=42
  _globals['_UPLOADDOCUMENTREQUEST']._serialized_end=102
  _globals['_UPLOADDOCUMENTRESPONSE']._serialized_start=104
  _globals['_UPLOADDOCUMENTRESPONSE']._serialized_end=145
  _globals['_SEARCHDOCUMENTSREQUEST']._serialized_start=147
  _globals['_SEARCHDOCUMENTSREQUEST']._serialized_end=201
  _globals['_SEARCHDOCUMENTSRESPONSE']._serialized_start=203
  _globals['_SEARCHDOCUMENTSRESPONSE']._serialized_end=276
  _globals['_SEARCHRESULT']._serialized_start=278
  _globals['_SEARCHRESULT']._serialized_end=383
  _globals['_SUMMARIZETEXTREQUEST']._serialized_start=385
  _globals['_SUMMARIZETEXTREQUEST']._serialized_end=421
  _globals['_SUMMARIZETEXTRESPONSE']._serialized_start=423
  _globals['_SUMMARIZETEXTRESPONSE']._serialized_end=463
  _globals['_VECTORDATABASE']._serialized_start=466
  _globals['_VECTORDATABASE']._serialized_end=779
# @@protoc_insertion_point(module_scope)
